[package]
name = "keyway"
version = "0.1.0"
edition = "2021"
authours = ["tkcd"]

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
input = "0.9.0"
libc = "0.2.155"
xkbcommon = "0.7.0"
