[package]
name = "keyway"
version = "0.1.0"
edition = "2021"
authours = ["tkcd"]

[dependencies]
async-channel = "2.3.1"
clap = { version = "4.5.9", features = ["derive"] }
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_6"] }
input = "0.9.0"
libc = "0.2.155"
xkbcommon = "0.7.0"
